# Generated by Django 4.2.19 on 2025-02-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.DeleteModel(
            name='TestModel2',
        ),
        migrations.DeleteModel(
            name='TestModel3',
        ),
    ]
