# Generated by Django 4.2.19 on 2025-03-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_testmodel_delete_testmodel2_delete_testmodel3'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_job_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
