# Generated by Django 4.2.19 on 2025-02-15 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_testmodel3'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('experience_level', models.CharField(max_length=255)),
                ('preferred_interview_type', models.JSONField()),
                ('preferred_language', models.CharField(max_length=255)),
                ('resume_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
