services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: careercracker-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: careercracker-frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: careercracker-db
    environment:
      POSTGRES_DB: careercracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
