services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: careercracker-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py makemigrations accounts interviews &&
             python manage.py migrate &&
             python manage.py loadquestions &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: careercracker-frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    stdin_open: true
    tty: true

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: careercracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
