# Generated by Django 4.2.19 on 2025-03-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='job_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
