# Generated by Django 4.2.19 on 2025-03-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interview_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='csquestion',
            name='job_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csquestion',
            name='category',
            field=models.CharField(choices=[('ALG', 'Algorithms'), ('DS', 'Data Structures'), ('OOP', 'Object-Oriented Programming'), ('DB', 'Databases'), ('OS', 'Operating Systems'), ('NUL', 'None')], max_length=3),
        ),
    ]
